### ISSUE TITLE
Support for type annotations?

### ISSUE THREAD

**Issue by Muream** [mottosso/cmdc#15]
I started using type annotations quite a lot these past months and I've grown to love them.

Since none of the Maya APIs are type annotated, every function takes and returns `Any`. This is really frustrating to work with as you need to explicitly specify the type of a lot of variables when that should be inferred.

I think it would be really nice if cmdc was fully type annotated and made that one of its primary goals.
I haven't looked into how to set that up much so I'm not sure if pybind supports this or if we'd need to also write `.pyi` stubs for that.

**Comment by Muream** [comment]
Looks like making `.pyi` stubs would be the way to go, pyright doesn't support extracting information out of `.pyd` files
https://github.com/microsoft/pylance-release/issues/70#issuecomment-655251489

Not yet sure if we'd need to make those manually or somehow generate them though.

I'm also wondering how they should be distributed?

**Comment by mottosso** [comment]
We could distribute any amount and type of files in the Maya module, the install would remain the same. So if `.pyi` is the way to go, that would work.

**Comment by ross-g** [comment]
I've used the `stubgen` tool (part of `mypy`) to generate `.pyi` stubs before, but results vary with how thorough the type annotations are. PyCharm will also generate it's own stub files for you in the background which you can repurpose.

Both methods would likely require some manual maintainence to be really useful.

**Comment by Muream** [comment]
This PR has most of the work done: https://github.com/mottosso/cmdc/pull/16

It uses `pybind11-stubgen` (which is meant to be merged into `stubgen`) to generate the stubs from the bindings.
I need to have a deeper look but since we're generating bindings from C++, everything is strongly typed and the generated stubs reflect that well. I'm hoping we'll get away without any manual editing of the stubs.

**Comment by Muream** [comment]
closed by #16
